default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  host: localhost
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: indovations_demo_development

test:
  <<: *default
  database: indovations_demo_test

production:
  <<: *default
  database: indovations_demo_production
  username: indovations_demo
  password: <%= ENV['INDOVATIONS_DEMO_DATABASE_PASSWORD'] %>
